[package]
name = "purescript-tuples"
version = "4.1.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-type-equality = "^2.1.0"
purescript-distributive = "^3.0.0"
purescript-foldable-traversable = "^3.0.0"
purescript-prelude = "^3.0.0"
