[package]
name = "purescript-arrays"
version = "4.1.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-unfoldable = "^3.0.0"
purescript-foldable-traversable = "^3.0.0"
purescript-tailrec = "^3.0.0"
purescript-st = "^3.0.0"
purescript-nonempty = "^4.0.0"
purescript-unsafe-coerce = "^3.0.0"
purescript-tuples = "^4.0.0"
purescript-partial = "^1.2.0"
