[package]
name = "purescript-transformers"
version = "3.4.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-arrays = "^4.0.0"
purescript-distributive = "^3.0.0"
purescript-lazy = "^3.0.0"
purescript-tuples = "^4.0.0"
