[package]
name = "purescript-exceptions"
version = "2.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^2.0.0"
purescript-maybe = "^2.0.0"
purescript-eff = "^2.0.0"
