[package]
name = "purescript-parallel"
version = "2.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-functors = "^1.0.0"
purescript-refs = "^2.0.0"
purescript-transformers = "^2.0.0"
