[package]
name = "purescript-profunctor"
version = "3.2.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^3.0.0"
purescript-exists = "^3.0.0"
purescript-distributive = "^3.0.0"
purescript-contravariant = "^3.0.0"
purescript-tuples = "^4.0.0"
