[package]
name = "purescript-foreign"
version = "3.2.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^2.0.0"
purescript-arrays = "^3.0.0"
purescript-foldable-traversable = "^2.0.0"
purescript-integers = "^2.0.0"
purescript-transformers = "^2.0.0"
purescript-strings = "^2.0.0"
purescript-lists = "^3.0.0"
purescript-functions = "^2.0.0"
