[package]
name = "purescript-generics"
version = "4.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-proxy = "^2.0.0"
purescript-either = "^3.0.0"
purescript-arrays = "^4.0.0"
purescript-strings = "^3.0.0"
purescript-identity = "^3.0.0"
purescript-lists = "^4.0.0"
