[package]
name = "purescript-contravariant"
version = "2.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^2.0.0"
purescript-monoid = "^2.0.0"
purescript-tuples = "^3.0.0"
