[package]
name = "purescript-integers"
version = "3.1.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-maybe = "^3.0.0"
purescript-globals = "^3.0.0"
purescript-math = "^2.0.0"
purescript-partial = "^1.2.0"
