[package]
name = "purescript-foreign"
version = "4.0.1"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^3.0.0"
purescript-arrays = "^4.0.0"
purescript-foldable-traversable = "^3.0.0"
purescript-integers = "^3.0.0"
purescript-transformers = "^3.0.0"
purescript-strings = "^3.0.0"
purescript-lists = "^4.0.0"
purescript-functions = "^3.0.0"
