[package]
name = "purescript-maps"
version = "3.3.1"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-arrays = "^4.0.0"
purescript-gen = "^1.1.0"
purescript-st = "^3.0.0"
purescript-lists = "^4.0.0"
purescript-functions = "^3.0.0"
