[package]
name = "purescript-catenable-lists"
version = "4.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-control = "^3.0.0"
purescript-unfoldable = "^3.0.0"
purescript-foldable-traversable = "^3.0.0"
purescript-tuples = "^4.0.0"
purescript-lists = "^4.0.0"
