[package]
name = "purescript-minibench"
version = "1.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-console = "^3.0.0"
purescript-prelude = "^3.0.0"
purescript-st = "^3.0.0"
purescript-integers = "^3.0.0"
purescript-partial = "^1.2.0"
