[package]
name = "purescript-tailrec"
version = "3.1.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^3.0.0"
purescript-st = "^3.0.0"
purescript-partial = "^1.2.0"
purescript-identity = "^3.0.0"
