[package]
name = "purescript-quickcheck"
version = "4.4.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-exceptions = "^3.0.0"
purescript-console = "^3.0.0"
purescript-either = "^3.0.0"
purescript-arrays = "^4.0.0"
purescript-gen = "^1.0.0"
purescript-nonempty = "^4.0.0"
purescript-transformers = "^3.0.0"
purescript-generics-rep = "^5.0.0"
purescript-enums = "^3.0.0"
purescript-random = "^3.0.0"
purescript-partial = "^1.2.0"
purescript-strings = "^3.0.0"
purescript-lists = "^4.0.0"
