[package]
name = "purescript-typelevel-prelude"
version = "2.2.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-proxy = "^2.0.0"
purescript-symbols = "^3.0.0"
purescript-type-equality = "^2.0.0"
