[package]
name = "purescript-functors"
version = "2.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^3.0.0"
purescript-unsafe-coerce = "^3.0.0"
purescript-const = "^3.0.0"
