[package]
name = "purescript-enums"
version = "3.1.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^3.0.0"
purescript-unfoldable = "^3.0.0"
purescript-strings = "^3.0.0"
