[package]
name = "purescript-exceptions"
version = "3.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-either = "^3.0.0"
purescript-maybe = "^3.0.0"
purescript-eff = "^3.0.0"
