[package]
name = "purescript-generics-rep"
version = "5.0.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-symbols = "^3.0.0"
purescript-monoid = "^3.0.0"
purescript-foldable-traversable = "^3.0.0"
purescript-prelude = "^3.0.0"
