[package]
name = "purescript-generics-rep"
version = "4.1.0"
compiler = ">= 0.11.5"
authors = ["author"]

[dependencies]
purescript-symbols = "^2.0.0"
purescript-monoid = "^2.0.0"
purescript-foldable-traversable = "^2.0.0"
purescript-prelude = "^2.0.0"
